### ISSUE TITLE
报如下错误是什么引起的呢

### ISSUE THREAD

**Issue by w-danboard** [Number314225/demo-react-express-upload#3]
[0] events.js:174
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0] 
[0] Error: listen EADDRINUSE: address already in use :::5000
[0]     at Server.setupListenHandle [as _listen2] (net.js:1279:14)
[0]     at listenInCluster (net.js:1327:12)
[0]     at Server.listen (net.js:1414:7)
[0]     at Function.listen (/Users/wanglin/Desktop/demo-react-express-upload/node_modules/express/lib/application.js:618:24)
[0]     at Object.<anonymous> (/Users/wanglin/Desktop/demo-react-express-upload/server.js:28:5)
[0]     at Module._compile (internal/modules/cjs/loader.js:778:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[0]     at Module.load (internal/modules/cjs/loader.js:653:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[0] Emitted 'error' event at:
[0]     at emitErrorNT (net.js:1306:8)
[0]     at process._tickCallback (internal/process/next_tick.js:63:19)
[0]     at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
[0]     at startup (internal/bootstrap/node.js:283:19)
[0]     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
[0] [nodemon] app crashed - waiting for file changes before starting...
[1] Something is already running on port 3000.
[1] npm run client exited with code 0

**Comment by w-danboard** [comment]
I have solved the problem
